package net.runelite.client.plugins.ElZMI;

public enum ElZMIState
{
	ANIMATING,
	NULL_PLAYER,
	TICK_TIMER,
	MOVING,
	OPENING_BANK,
	MISSING_REQUIRED,
	CLICKING_ALTAR,
	EMPTYING_POUCHES,
	TELEPORT_OURANIA,
	CLICKING_LADDER,
	DEPOSIT_INVENT,
	PLAYER_HP_LOW,
	MISSING_RUNE_POUCH,
	DRINKING_STAM,
	WITHDRAW_STAM,
	EATING_FOOD,
	WITHDRAW_FOOD,
	FILL_GIANT,
	FILL_LARGE,
	FILL_MEDIUM,
	FILL_SMALL,
	CLOSING_BANK,
	WITHDRAW_ESS,
	EMPTY_SMALL,
	EMPTY_GIANT,
	EMPTY_LARGE,
	EMPTY_MEDIUM,
	POUCH_DEGRADED,
	UNKNOWN;
}
