package net.runelite.client.plugins.ElAirs;

public enum ElAirsState
{
	ANIMATING,
	MOVING,
	TIMEOUT,
	BANK_NOT_FOUND,
	FIND_BANK,
	DEPOSIT_ITEMS,
	HANDLE_BREAK,
	USE_SHORTCUT,
	CRAFT_TIARAS,
	ENTER_ALTAR,
	CRAFT_RUNES,
	USE_PORTAL,
	WALK_FIRST_POINT,
	WALK_SECOND_POINT,
	WITHDRAW_ITEMS,
	UNHANDLED_STATE;
}
