package net.runelite.client.plugins.ElKarambwans;

public enum ElKarambwansState
{
	ANIMATING,
	FIND_NPC,
	MISSING_ITEMS,
	MOVING,
	TIMEOUT,
	BANK_NOT_FOUND,
	FIND_BANK,
	DEPOSIT_ITEMS,
	HANDLE_BREAK,
	USE_FAIRY_RING_1,
	USE_FAIRY_RING_2,
	WALK_TO_MIDDLE,
	WALK_TO_BANK,
	UNHANDLED_STATE;
}
