package net.runelite.client.plugins.ElSandstone;

public enum ElSandstoneState
{
	ANIMATING,
	FIND_GAME_OBJECT,
	HANDLE_BREAK,
	ITERATING,
	MOVING,
	TIMEOUT,
	ADDING_SANDSTONE_TO_GRINDER,
	WALKING_BACK_TO_SANDSTONE,
	CASTING_HUMIDIFY;
}
